### ISSUE TITLE
<package>#2.0.1 does not satisfy ~2.0.1

### ISSUE THREAD

**Issue by mr-moon** [mokkabonna/grunt-bower-verify#8]
Looks like it cannot verify `~2.0.1` against `2.0.1`, which is perfectly valid.

**Comment by mokkabonna** [comment]
I had some similar issues myself, but I think the update from old semver fixed this:

https://github.com/mokkabonna/grunt-bower-verify/commit/0e1f66010fac27424b19fb69660c5346970d1111

Repoen if not fixed.
